name: puzzle
description: A puzzle game

publish_to: 'none'

version: 0.1.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^16.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flame: ^1.30.1
  flame_audio: ^2.10.2
  infinite_scroll_pagination: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: any
  flutter_screenutil: ^5.9.3
  card_swiper: ^3.0.1
  awesome_dialog: ^3.2.1
  lottie: any
  mime: ^2.0.0
  cherry_toast: ^1.10.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  file: any
  crypto: ^3.0.3
  http: any
  image: ^4.1.3
  file_selector: any
  path_provider: ^2.1.5

dependency_overrides: 
  path_provider: 
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/path_provider/path_provider"
  device_info_plus:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/device_info_plus/device_info_plus"

  url_launcher:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/url_launcher/url_launcher"

  file_selector:
    git: 
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/file_selector/file_selector"
  # Android 平台时可启用 OHOS 分支；为确保 Web 构建兼容，这里关闭 audioplayers 的 git 覆盖
  # audioplayers:
  #   git:
  #     url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
  #     path: packages/audioplayers
  #     ref: br_v6.5.0_ohos

  # audioplayers_platform_interface: 
  #   git: 
  #     url: https://gitcode.com/openharmony-sig/flutter_audioplayers.git
  #     path: packages/audioplayers_platform_interface
  #     ref: br_v6.5.0_ohos

  shared_preferences:
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"
      ref: "br_shared_preferences-v2.5.3_ohos"

  package_info_plus:
    git:
      url: "https://gitcode.com/openharmony-sig/flutter_plus_plugins.git"
      path: "packages/package_info_plus/package_info_plus"
      ref: "br_package_info_plus_v8.3.0_ohos"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  test: ^1.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/animals/
    - assets/images/landscape/
    - assets/images/people/
    - assets/images/cars/
    - assets/images/beauty/
    - assets/images/architecture/
    - assets/music/
    - assets/sfx/
    - assets/lottie/
    - assets/audio/
    - assets/icon/

