name: flutter_jigsaw_puzzle
description: A jigsaw puzzle game

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^16.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
#  carousel_slider: ^4.2.1
#  google_mobile_ads: ^3.0.0  # Ads
  flame: ^1.30.1
  flame_audio: ^2.10.2
  infinite_scroll_pagination: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.2
#  flutter_image_compress: ^2.0.3
  flutter_screenutil: ^5.9.3
  card_swiper: ^3.0.1
  awesome_dialog: ^3.2.1
  lottie: ^3.3.1
  mime: ^2.0.0
  cherry_toast: ^1.10.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_analytics: ^11.5.2
#  mixpanel_flutter: ^2.0.0

dev_dependencies:
#  analysis_defaults:
#    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/
    - assets/lottie/
    - assets/audio/

