// Mocks generated by Mockito 5.4.6 from annotations
// in puzzle/test/src/settings/settings_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:puzzle/src/settings/persistence/settings_persistence.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SettingsPersistence].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsPersistence extends _i1.Mock
    implements _i2.SettingsPersistence {
  MockSettingsPersistence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> getMusicOn() => (super.noSuchMethod(
        Invocation.method(
          #getMusicOn,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> getMuted({required bool? defaultValue}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMuted,
          [],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String> getPlayerName() => (super.noSuchMethod(
        Invocation.method(
          #getPlayerName,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getPlayerName,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> getSoundsOn() => (super.noSuchMethod(
        Invocation.method(
          #getSoundsOn,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> saveMusicOn(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #saveMusicOn,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveMuted(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #saveMuted,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> savePlayerName(String? value) => (super.noSuchMethod(
        Invocation.method(
          #savePlayerName,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveSoundsOn(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #saveSoundsOn,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
