// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZOSj1yyluv7MimGdmkHKIAWSVy6U59E',
    appId: '1:414324934045:web:430d89aef8165cfe1d9b74',
    messagingSenderId: '414324934045',
    projectId: 'puzzle-738d3',
    authDomain: 'puzzle-738d3.firebaseapp.com',
    storageBucket: 'puzzle-738d3.firebasestorage.app',
    measurementId: 'G-GHVCMVV4VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtifPaEZMt4wPy-QdRKHHbQV2vfNVCiLE',
    appId: '1:414324934045:android:7f418435bab075531d9b74',
    messagingSenderId: '414324934045',
    projectId: 'puzzle-738d3',
    storageBucket: 'puzzle-738d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbQB6i_s7AXb2uuArFvi50VdlxiheD9_A',
    appId: '1:414324934045:ios:25738de72f84b5151d9b74',
    messagingSenderId: '414324934045',
    projectId: 'puzzle-738d3',
    storageBucket: 'puzzle-738d3.firebasestorage.app',
    iosBundleId: 'run.oldbird.puzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbQB6i_s7AXb2uuArFvi50VdlxiheD9_A',
    appId: '1:414324934045:ios:0a0f701ba19a73611d9b74',
    messagingSenderId: '414324934045',
    projectId: 'puzzle-738d3',
    storageBucket: 'puzzle-738d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterPuzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhZOSj1yyluv7MimGdmkHKIAWSVy6U59E',
    appId: '1:414324934045:web:40da22d897aa33a61d9b74',
    messagingSenderId: '414324934045',
    projectId: 'puzzle-738d3',
    authDomain: 'puzzle-738d3.firebaseapp.com',
    storageBucket: 'puzzle-738d3.firebasestorage.app',
    measurementId: 'G-3483287WSW',
  );
}
